/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airport_reservation_system;

import javax.swing.JDesktopPane;

/**
 *
 * @author ADITYA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        AddCustomer = new javax.swing.JMenuItem();
        SearchCustomer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AddFlight = new javax.swing.JMenuItem();
        BookFight = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        AddAdmin = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        GetTicket = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        jMenu3.setText("Customer");

        AddCustomer.setText("Add Customer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(AddCustomer);

        SearchCustomer.setText("Search Customer");
        SearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(SearchCustomer);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Flight");

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });
        jMenu4.add(AddFlight);

        BookFight.setText("Book Flight");
        BookFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFightActionPerformed(evt);
            }
        });
        jMenu4.add(BookFight);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Admin");

        AddAdmin.setText("Add Admin");
        AddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminActionPerformed(evt);
            }
        });
        jMenu6.add(AddAdmin);

        jMenuBar2.add(jMenu6);

        jMenu5.setText("Ticket");

        GetTicket.setText("View Ticket");
        GetTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetTicketActionPerformed(evt);
            }
        });
        jMenu5.add(GetTicket);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
         // TODO add your handling code here:
         AddCustomer customer = new AddCustomer(); 
         Desktop.add(customer);
         customer.setVisible(true);
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void AddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminActionPerformed
        // TODO add your handling code here:
        AddAdmin admin = new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_AddAdminActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void BookFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFightActionPerformed
        // TODO add your handling code here:
        BookTicket newTicket = new BookTicket();
        Desktop.add(newTicket);
        newTicket.setVisible(true);
    }//GEN-LAST:event_BookFightActionPerformed

    private void SearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerActionPerformed
        // TODO add your handling code here:
        SearchCustomer searchCustomer = new SearchCustomer();
        Desktop.add(searchCustomer);
        searchCustomer.setVisible(true);
    }//GEN-LAST:event_SearchCustomerActionPerformed

    private void GetTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetTicketActionPerformed
        // TODO add your handling code here:
        GetTicket ticket = new GetTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_GetTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAdmin;
    private javax.swing.JMenuItem AddCustomer;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem BookFight;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem GetTicket;
    private javax.swing.JMenuItem SearchCustomer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables

    void setVissble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
