/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airport_reservation_system;

import javax.swing.JDesktopPane;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author ADITYA
 */
public class Main extends javax.swing.JFrame {
    
    class BackgroundDesktop extends javax.swing.JDesktopPane {
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                            java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        // ── Dark blue gradient background ────────────────────
        java.awt.GradientPaint gradient = new java.awt.GradientPaint(
            0, 0,                              // top-left
            new java.awt.Color(10, 20, 60),    // dark navy
            getWidth(), getHeight(),            // bottom-right
            new java.awt.Color(30, 58, 138)    // PRIMARY blue
        );
        g2.setPaint(gradient);
        g2.fillRect(0, 0, getWidth(), getHeight());

        // ── Subtle grid lines ────────────────────────────────
        g2.setColor(new java.awt.Color(255, 255, 255, 15));
        g2.setStroke(new java.awt.BasicStroke(1));
        for (int x = 0; x < getWidth(); x += 60) {
            g2.drawLine(x, 0, x, getHeight());
        }
        for (int y = 0; y < getHeight(); y += 60) {
            g2.drawLine(0, y, getWidth(), y);
        }

        // ── Center text watermark ────────────────────────────
        g2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 48));
        g2.setColor(new java.awt.Color(255, 255, 255, 20));
        String text = "✈  AIRPORT RESERVATION SYSTEM";
        java.awt.FontMetrics fm = g2.getFontMetrics();
        int x = (getWidth() - fm.stringWidth(text)) / 2;
        int y = getHeight() / 2;
        g2.drawString(text, x, y);

        g2.dispose();
    }
}


    
    public Main() {
        
        initComponents();
        
        Desktop = new BackgroundDesktop();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(Desktop, java.awt.BorderLayout.CENTER);
        
        
        
        javax.swing.JMenuBar transparentBar = new javax.swing.JMenuBar() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new java.awt.Color(30, 58, 138, 200));
                g2.fillRect(0, 0, getWidth(), getHeight());
                g2.dispose();
            }
        };
        transparentBar.setOpaque(false);
        transparentBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 4, 2, 4));

        // ── Move all menus to new bar ────────────────────────────
        while (jMenuBar2.getMenuCount() > 0) {
            javax.swing.JMenu menu = jMenuBar2.getMenu(0);
            if (menu != null) {
                menu.setForeground(java.awt.Color.WHITE);
                menu.setFont(AppTheme.FONT_BUTTON);
                menu.setOpaque(false);
                menu.setBorderPainted(false);

                for (int j = 0; j < menu.getItemCount(); j++) {
                    javax.swing.JMenuItem item = menu.getItem(j);
                    if (item == null) continue;
                    item.setFont(AppTheme.FONT_INPUT);
                    item.setBackground(AppTheme.INPUT_BG);
                    item.setForeground(AppTheme.TEXT_DARK);
                    item.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 12, 6, 12));
                }
                transparentBar.add(menu);
            } else {
                jMenuBar2.remove(0);
            }
        }

        setJMenuBar(transparentBar);
        revalidate();
        repaint();
        
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        AddCustomer = new javax.swing.JMenuItem();
        SearchCustomer = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AddFlight = new javax.swing.JMenuItem();
        BookFlight = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        AddAdmin = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        GetTicket = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));

        jMenu3.setText("Customer");

        AddCustomer.setText("Add Customer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(AddCustomer);

        SearchCustomer.setText("Search Customer");
        SearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(SearchCustomer);

        jMenuItem2.setText("Delete Customer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("UpdateCustomer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Flight");
        jMenu4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu4StateChanged(evt);
            }
        });

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });
        jMenu4.add(AddFlight);

        BookFlight.setText("Book Flight");
        BookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightActionPerformed(evt);
            }
        });
        jMenu4.add(BookFlight);

        jMenuItem4.setText("Cancel Flight");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Admin");

        AddAdmin.setText("Add Admin");
        AddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminActionPerformed(evt);
            }
        });
        jMenu6.add(AddAdmin);

        jMenuItem1.setText("Delete Access");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar2.add(jMenu6);

        jMenu5.setText("Ticket");

        GetTicket.setText("View Ticket");
        GetTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetTicketActionPerformed(evt);
            }
        });
        jMenu5.add(GetTicket);

        jMenuItem5.setText("Cancel Ticket");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("View");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Customer Data");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setText("Flight Data ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Ticket Data");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Setting");

        jMenuItem9.setForeground(new java.awt.Color(204, 0, 51));
        jMenuItem9.setText("Logout");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
         // TODO add your handling code here:
         AddCustomer customer = new AddCustomer();
         for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
         Desktop.add(customer);
         customer.setVisible(true);
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void AddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminActionPerformed
        // TODO add your handling code here:
        AddAdmin admin = new AddAdmin();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_AddAdminActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void BookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightActionPerformed
        // TODO add your handling code here:
        BookTicket newTicket = new BookTicket();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(newTicket);
        newTicket.setVisible(true);
    }//GEN-LAST:event_BookFlightActionPerformed

    private void SearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerActionPerformed
        // TODO add your handling code here:
        SearchCustomer searchCustomer = new SearchCustomer();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(searchCustomer);
        searchCustomer.setVisible(true);
    }//GEN-LAST:event_SearchCustomerActionPerformed

    private void GetTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetTicketActionPerformed
        // TODO add your handling code here:
        GetTicket ticket = new GetTicket();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_GetTicketActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DeleteAdmin Access = new DeleteAdmin();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(Access);
       Access.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DeleteCustomer info = new DeleteCustomer();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(info);
       info.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        UpdateCustomer Uinfo = new UpdateCustomer();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(Uinfo);
       Uinfo.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4StateChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DeleteFlight cancle = new DeleteFlight();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(cancle);
       cancle.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CancleTicket reject = new CancleTicket();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(reject);
       reject.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       CustomerData Cdata = new CustomerData();
       for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(Cdata);
       Cdata.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        TicketData Tdata = new TicketData();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }
        Desktop.add(Tdata);
       Tdata.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        FlightData Fdata = new FlightData();
        for (JInternalFrame frame : Desktop.getAllFrames()) {
            frame.dispose();  // or frame.setVisible(false);
            }

        Desktop.add(Fdata);
       Fdata.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAdmin;
    private javax.swing.JMenuItem AddCustomer;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem BookFlight;
    private javax.swing.JMenuItem GetTicket;
    private javax.swing.JMenuItem SearchCustomer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
javax.swing.JDesktopPane Desktop;
    void setVissble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
